// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPiv4eF8oWlylRLb56AbLbrPwo7enhLZY',
    appId: '1:859739397646:web:2f6e0e6bc58c06f0bba65f',
    messagingSenderId: '859739397646',
    projectId: 'brew-view-b04f3',
    authDomain: 'brew-view-b04f3.firebaseapp.com',
    databaseURL: 'https://brew-view-b04f3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'brew-view-b04f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9DFIGdCcr_OTHK1UY-aJAn6D3v3nI8nY',
    appId: '1:859739397646:android:bd2e3ff04a4a28c6bba65f',
    messagingSenderId: '859739397646',
    projectId: 'brew-view-b04f3',
    databaseURL: 'https://brew-view-b04f3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'brew-view-b04f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8q2aaFehxEb-xinsT8ZW7pZ7fvV7EJ2o',
    appId: '1:859739397646:ios:3b1dc9758acc2810bba65f',
    messagingSenderId: '859739397646',
    projectId: 'brew-view-b04f3',
    databaseURL: 'https://brew-view-b04f3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'brew-view-b04f3.firebasestorage.app',
    androidClientId: '859739397646-5r8lnut5g7u7000imivkorjdfvcktm97.apps.googleusercontent.com',
    iosClientId: '859739397646-bo23cds9v87krrfhe35m05hes2bafssd.apps.googleusercontent.com',
    iosBundleId: 'com.example.briewview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8q2aaFehxEb-xinsT8ZW7pZ7fvV7EJ2o',
    appId: '1:859739397646:ios:3b1dc9758acc2810bba65f',
    messagingSenderId: '859739397646',
    projectId: 'brew-view-b04f3',
    databaseURL: 'https://brew-view-b04f3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'brew-view-b04f3.firebasestorage.app',
    androidClientId: '859739397646-5r8lnut5g7u7000imivkorjdfvcktm97.apps.googleusercontent.com',
    iosClientId: '859739397646-bo23cds9v87krrfhe35m05hes2bafssd.apps.googleusercontent.com',
    iosBundleId: 'com.example.briewview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPiv4eF8oWlylRLb56AbLbrPwo7enhLZY',
    appId: '1:859739397646:web:1078f23208fb6c2cbba65f',
    messagingSenderId: '859739397646',
    projectId: 'brew-view-b04f3',
    authDomain: 'brew-view-b04f3.firebaseapp.com',
    databaseURL: 'https://brew-view-b04f3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'brew-view-b04f3.firebasestorage.app',
  );
}
